version: "3"

services:
  staging:
    image: tomcat
    ports:
      - 8080:8080
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
  production:
    image: tomcat
    ports:
      - 9090:8080
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
