version: "3"

services:
  web:
    image: drupal
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypass
    volumes:
      - 07-data:/var/lib/postgresql/data

volumes:
  07-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

