pipeline {
    agent any
    
	stages{
        stage('Build'){
            steps {
                powershell '''
                    cd udemy/jenkins/jenkinspipeline
                    mvn clean package
                '''
            }
            post {
                success {
                    echo $(pwd)
                    echo "Now Archiving..."
                    archiveArtifacts artifacts: "**/target/*.war"
                }
            }
        }
    }
}