pipeline {
    agent any
    
    parameters {
        string(name: 'project_root', defaultValue: 'udemy/jenkins/jenkinspipeline', description: 'Maven project root folder')
    }
	
    stages{
        stage('Build'){
            steps {
                dir (params.project_root) {
                    powershell "mvn clean package"
                }
            }
            post {
                success {
                    dir (params.project_root) {
                        echo "Now Archiving..."
                        archiveArtifacts artifacts: "**/target/*.war"
                    }   
                }
            }
        }
    }
}